// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: basic-test/clientstream-api.proto

package basic_test

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Data Structure
type DataUploadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DataUploadMessage) Reset() {
	*x = DataUploadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_clientstream_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUploadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUploadMessage) ProtoMessage() {}

func (x *DataUploadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_clientstream_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUploadMessage.ProtoReflect.Descriptor instead.
func (*DataUploadMessage) Descriptor() ([]byte, []int) {
	return file_basic_test_clientstream_api_proto_rawDescGZIP(), []int{0}
}

func (x *DataUploadMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DataUploadMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//Request and Response Payload
type DataUploadMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *DataUploadMessage `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DataUploadMessageRequest) Reset() {
	*x = DataUploadMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_clientstream_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUploadMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUploadMessageRequest) ProtoMessage() {}

func (x *DataUploadMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_clientstream_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUploadMessageRequest.ProtoReflect.Descriptor instead.
func (*DataUploadMessageRequest) Descriptor() ([]byte, []int) {
	return file_basic_test_clientstream_api_proto_rawDescGZIP(), []int{1}
}

func (x *DataUploadMessageRequest) GetPayload() *DataUploadMessage {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DataUploadMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode string `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
}

func (x *DataUploadMessageResponse) Reset() {
	*x = DataUploadMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_clientstream_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUploadMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUploadMessageResponse) ProtoMessage() {}

func (x *DataUploadMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_clientstream_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUploadMessageResponse.ProtoReflect.Descriptor instead.
func (*DataUploadMessageResponse) Descriptor() ([]byte, []int) {
	return file_basic_test_clientstream_api_proto_rawDescGZIP(), []int{2}
}

func (x *DataUploadMessageResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

var File_basic_test_clientstream_api_proto protoreflect.FileDescriptor

var file_basic_test_clientstream_api_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x22,
	0x45, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x18, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3b, 0x0a, 0x19, 0x44,
	0x61, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x80, 0x01, 0x0a, 0x18, 0x44, 0x61, 0x74,
	0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x17, 0x5a, 0x15, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f,
	0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_basic_test_clientstream_api_proto_rawDescOnce sync.Once
	file_basic_test_clientstream_api_proto_rawDescData = file_basic_test_clientstream_api_proto_rawDesc
)

func file_basic_test_clientstream_api_proto_rawDescGZIP() []byte {
	file_basic_test_clientstream_api_proto_rawDescOnce.Do(func() {
		file_basic_test_clientstream_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_basic_test_clientstream_api_proto_rawDescData)
	})
	return file_basic_test_clientstream_api_proto_rawDescData
}

var file_basic_test_clientstream_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_basic_test_clientstream_api_proto_goTypes = []interface{}{
	(*DataUploadMessage)(nil),         // 0: basic_test.DataUploadMessage
	(*DataUploadMessageRequest)(nil),  // 1: basic_test.DataUploadMessageRequest
	(*DataUploadMessageResponse)(nil), // 2: basic_test.DataUploadMessageResponse
}
var file_basic_test_clientstream_api_proto_depIdxs = []int32{
	0, // 0: basic_test.DataUploadMessageRequest.payload:type_name -> basic_test.DataUploadMessage
	1, // 1: basic_test.DataUploadMessageService.DataUploadMessage:input_type -> basic_test.DataUploadMessageRequest
	2, // 2: basic_test.DataUploadMessageService.DataUploadMessage:output_type -> basic_test.DataUploadMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basic_test_clientstream_api_proto_init() }
func file_basic_test_clientstream_api_proto_init() {
	if File_basic_test_clientstream_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_basic_test_clientstream_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUploadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_clientstream_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUploadMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_clientstream_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUploadMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basic_test_clientstream_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_test_clientstream_api_proto_goTypes,
		DependencyIndexes: file_basic_test_clientstream_api_proto_depIdxs,
		MessageInfos:      file_basic_test_clientstream_api_proto_msgTypes,
	}.Build()
	File_basic_test_clientstream_api_proto = out.File
	file_basic_test_clientstream_api_proto_rawDesc = nil
	file_basic_test_clientstream_api_proto_goTypes = nil
	file_basic_test_clientstream_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataUploadMessageServiceClient is the client API for DataUploadMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataUploadMessageServiceClient interface {
	//Client-Streaming API
	DataUploadMessage(ctx context.Context, opts ...grpc.CallOption) (DataUploadMessageService_DataUploadMessageClient, error)
}

type dataUploadMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataUploadMessageServiceClient(cc grpc.ClientConnInterface) DataUploadMessageServiceClient {
	return &dataUploadMessageServiceClient{cc}
}

func (c *dataUploadMessageServiceClient) DataUploadMessage(ctx context.Context, opts ...grpc.CallOption) (DataUploadMessageService_DataUploadMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataUploadMessageService_serviceDesc.Streams[0], "/basic_test.DataUploadMessageService/DataUploadMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataUploadMessageServiceDataUploadMessageClient{stream}
	return x, nil
}

type DataUploadMessageService_DataUploadMessageClient interface {
	Send(*DataUploadMessageRequest) error
	CloseAndRecv() (*DataUploadMessageResponse, error)
	grpc.ClientStream
}

type dataUploadMessageServiceDataUploadMessageClient struct {
	grpc.ClientStream
}

func (x *dataUploadMessageServiceDataUploadMessageClient) Send(m *DataUploadMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataUploadMessageServiceDataUploadMessageClient) CloseAndRecv() (*DataUploadMessageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DataUploadMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataUploadMessageServiceServer is the server API for DataUploadMessageService service.
type DataUploadMessageServiceServer interface {
	//Client-Streaming API
	DataUploadMessage(DataUploadMessageService_DataUploadMessageServer) error
}

// UnimplementedDataUploadMessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataUploadMessageServiceServer struct {
}

func (*UnimplementedDataUploadMessageServiceServer) DataUploadMessage(DataUploadMessageService_DataUploadMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method DataUploadMessage not implemented")
}

func RegisterDataUploadMessageServiceServer(s *grpc.Server, srv DataUploadMessageServiceServer) {
	s.RegisterService(&_DataUploadMessageService_serviceDesc, srv)
}

func _DataUploadMessageService_DataUploadMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataUploadMessageServiceServer).DataUploadMessage(&dataUploadMessageServiceDataUploadMessageServer{stream})
}

type DataUploadMessageService_DataUploadMessageServer interface {
	SendAndClose(*DataUploadMessageResponse) error
	Recv() (*DataUploadMessageRequest, error)
	grpc.ServerStream
}

type dataUploadMessageServiceDataUploadMessageServer struct {
	grpc.ServerStream
}

func (x *dataUploadMessageServiceDataUploadMessageServer) SendAndClose(m *DataUploadMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataUploadMessageServiceDataUploadMessageServer) Recv() (*DataUploadMessageRequest, error) {
	m := new(DataUploadMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DataUploadMessageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basic_test.DataUploadMessageService",
	HandlerType: (*DataUploadMessageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataUploadMessage",
			Handler:       _DataUploadMessageService_DataUploadMessage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "basic-test/clientstream-api.proto",
}
