// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: basic-test/unary-api.proto

package basic_test

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Data Structure
type HealthCheckStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName       string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppReleaseVer string `protobuf:"bytes,2,opt,name=app_release_ver,json=appReleaseVer,proto3" json:"app_release_ver,omitempty"`
}

func (x *HealthCheckStatus) Reset() {
	*x = HealthCheckStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckStatus) ProtoMessage() {}

func (x *HealthCheckStatus) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckStatus.ProtoReflect.Descriptor instead.
func (*HealthCheckStatus) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckStatus) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *HealthCheckStatus) GetAppReleaseVer() string {
	if x != nil {
		return x.AppReleaseVer
	}
	return ""
}

type Calculator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumOne int32 `protobuf:"varint,1,opt,name=num_one,json=numOne,proto3" json:"num_one,omitempty"`
	NumTwo int32 `protobuf:"varint,2,opt,name=num_two,json=numTwo,proto3" json:"num_two,omitempty"`
}

func (x *Calculator) Reset() {
	*x = Calculator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calculator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calculator) ProtoMessage() {}

func (x *Calculator) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calculator.ProtoReflect.Descriptor instead.
func (*Calculator) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{1}
}

func (x *Calculator) GetNumOne() int32 {
	if x != nil {
		return x.NumOne
	}
	return 0
}

func (x *Calculator) GetNumTwo() int32 {
	if x != nil {
		return x.NumTwo
	}
	return 0
}

//Request and Response Payload
type HealthCheckStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppName string `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *HealthCheckStatusRequest) Reset() {
	*x = HealthCheckStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckStatusRequest) ProtoMessage() {}

func (x *HealthCheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckStatusRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckStatusRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type HealthCheckStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HealthStatus *HealthCheckStatus `protobuf:"bytes,1,opt,name=healthStatus,proto3" json:"healthStatus,omitempty"`
}

func (x *HealthCheckStatusResponse) Reset() {
	*x = HealthCheckStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckStatusResponse) ProtoMessage() {}

func (x *HealthCheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckStatusResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckStatusResponse) GetHealthStatus() *HealthCheckStatus {
	if x != nil {
		return x.HealthStatus
	}
	return nil
}

type CalculatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *Calculator `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *CalculatorRequest) Reset() {
	*x = CalculatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorRequest) ProtoMessage() {}

func (x *CalculatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorRequest.ProtoReflect.Descriptor instead.
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{4}
}

func (x *CalculatorRequest) GetPayload() *Calculator {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CalculatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalculatorResponse) Reset() {
	*x = CalculatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_test_unary_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatorResponse) ProtoMessage() {}

func (x *CalculatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_test_unary_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatorResponse.ProtoReflect.Descriptor instead.
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return file_basic_test_unary_api_proto_rawDescGZIP(), []int{5}
}

func (x *CalculatorResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_basic_test_unary_api_proto protoreflect.FileDescriptor

var file_basic_test_unary_api_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x75, 0x6e, 0x61,
	0x72, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x5f,
	0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x56, 0x65, 0x72,
	0x22, 0x3e, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6e, 0x75, 0x6d, 0x4f, 0x6e, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x5f, 0x74,
	0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x54, 0x77, 0x6f,
	0x22, 0x35, 0x0a, 0x18, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5e, 0x0a, 0x19, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2c,
	0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x7e, 0x0a, 0x18,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x62, 0x0a, 0x11,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x1d, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x17, 0x5a, 0x15, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_basic_test_unary_api_proto_rawDescOnce sync.Once
	file_basic_test_unary_api_proto_rawDescData = file_basic_test_unary_api_proto_rawDesc
)

func file_basic_test_unary_api_proto_rawDescGZIP() []byte {
	file_basic_test_unary_api_proto_rawDescOnce.Do(func() {
		file_basic_test_unary_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_basic_test_unary_api_proto_rawDescData)
	})
	return file_basic_test_unary_api_proto_rawDescData
}

var file_basic_test_unary_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_basic_test_unary_api_proto_goTypes = []interface{}{
	(*HealthCheckStatus)(nil),         // 0: basic_test.HealthCheckStatus
	(*Calculator)(nil),                // 1: basic_test.Calculator
	(*HealthCheckStatusRequest)(nil),  // 2: basic_test.HealthCheckStatusRequest
	(*HealthCheckStatusResponse)(nil), // 3: basic_test.HealthCheckStatusResponse
	(*CalculatorRequest)(nil),         // 4: basic_test.CalculatorRequest
	(*CalculatorResponse)(nil),        // 5: basic_test.CalculatorResponse
}
var file_basic_test_unary_api_proto_depIdxs = []int32{
	0, // 0: basic_test.HealthCheckStatusResponse.healthStatus:type_name -> basic_test.HealthCheckStatus
	1, // 1: basic_test.CalculatorRequest.payload:type_name -> basic_test.Calculator
	2, // 2: basic_test.HealthCheckStatusService.HealthCheckStatus:input_type -> basic_test.HealthCheckStatusRequest
	4, // 3: basic_test.CalculatorService.Calculator:input_type -> basic_test.CalculatorRequest
	3, // 4: basic_test.HealthCheckStatusService.HealthCheckStatus:output_type -> basic_test.HealthCheckStatusResponse
	5, // 5: basic_test.CalculatorService.Calculator:output_type -> basic_test.CalculatorResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_basic_test_unary_api_proto_init() }
func file_basic_test_unary_api_proto_init() {
	if File_basic_test_unary_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_basic_test_unary_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_unary_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calculator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_unary_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_unary_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_unary_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_test_unary_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basic_test_unary_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_basic_test_unary_api_proto_goTypes,
		DependencyIndexes: file_basic_test_unary_api_proto_depIdxs,
		MessageInfos:      file_basic_test_unary_api_proto_msgTypes,
	}.Build()
	File_basic_test_unary_api_proto = out.File
	file_basic_test_unary_api_proto_rawDesc = nil
	file_basic_test_unary_api_proto_goTypes = nil
	file_basic_test_unary_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HealthCheckStatusServiceClient is the client API for HealthCheckStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthCheckStatusServiceClient interface {
	//Unary API
	HealthCheckStatus(ctx context.Context, in *HealthCheckStatusRequest, opts ...grpc.CallOption) (*HealthCheckStatusResponse, error)
}

type healthCheckStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckStatusServiceClient(cc grpc.ClientConnInterface) HealthCheckStatusServiceClient {
	return &healthCheckStatusServiceClient{cc}
}

func (c *healthCheckStatusServiceClient) HealthCheckStatus(ctx context.Context, in *HealthCheckStatusRequest, opts ...grpc.CallOption) (*HealthCheckStatusResponse, error) {
	out := new(HealthCheckStatusResponse)
	err := c.cc.Invoke(ctx, "/basic_test.HealthCheckStatusService/HealthCheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckStatusServiceServer is the server API for HealthCheckStatusService service.
type HealthCheckStatusServiceServer interface {
	//Unary API
	HealthCheckStatus(context.Context, *HealthCheckStatusRequest) (*HealthCheckStatusResponse, error)
}

// UnimplementedHealthCheckStatusServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHealthCheckStatusServiceServer struct {
}

func (*UnimplementedHealthCheckStatusServiceServer) HealthCheckStatus(context.Context, *HealthCheckStatusRequest) (*HealthCheckStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheckStatus not implemented")
}

func RegisterHealthCheckStatusServiceServer(s *grpc.Server, srv HealthCheckStatusServiceServer) {
	s.RegisterService(&_HealthCheckStatusService_serviceDesc, srv)
}

func _HealthCheckStatusService_HealthCheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckStatusServiceServer).HealthCheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basic_test.HealthCheckStatusService/HealthCheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckStatusServiceServer).HealthCheckStatus(ctx, req.(*HealthCheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HealthCheckStatusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basic_test.HealthCheckStatusService",
	HandlerType: (*HealthCheckStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheckStatus",
			Handler:    _HealthCheckStatusService_HealthCheckStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basic-test/unary-api.proto",
}

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error)
}

type calculatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorServiceClient(cc grpc.ClientConnInterface) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Calculator(ctx context.Context, in *CalculatorRequest, opts ...grpc.CallOption) (*CalculatorResponse, error) {
	out := new(CalculatorResponse)
	err := c.cc.Invoke(ctx, "/basic_test.CalculatorService/Calculator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Calculator(context.Context, *CalculatorRequest) (*CalculatorResponse, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Calculator(context.Context, *CalculatorRequest) (*CalculatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculator not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Calculator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Calculator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basic_test.CalculatorService/Calculator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Calculator(ctx, req.(*CalculatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "basic_test.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculator",
			Handler:    _CalculatorService_Calculator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basic-test/unary-api.proto",
}
