// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: message-post/message-post.proto

package message_post

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Data Structure
type MessagePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email       string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Message     string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessagePost) Reset() {
	*x = MessagePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_post_message_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePost) ProtoMessage() {}

func (x *MessagePost) ProtoReflect() protoreflect.Message {
	mi := &file_message_post_message_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePost.ProtoReflect.Descriptor instead.
func (*MessagePost) Descriptor() ([]byte, []int) {
	return file_message_post_message_post_proto_rawDescGZIP(), []int{0}
}

func (x *MessagePost) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *MessagePost) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *MessagePost) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *MessagePost) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MessagePost) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//Request and Response
type MessagePostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *MessagePost `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
}

func (x *MessagePostRequest) Reset() {
	*x = MessagePostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_post_message_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePostRequest) ProtoMessage() {}

func (x *MessagePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_post_message_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePostRequest.ProtoReflect.Descriptor instead.
func (*MessagePostRequest) Descriptor() ([]byte, []int) {
	return file_message_post_message_post_proto_rawDescGZIP(), []int{1}
}

func (x *MessagePostRequest) GetPost() *MessagePost {
	if x != nil {
		return x.Post
	}
	return nil
}

type MessagePostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId     string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageStatus int32  `protobuf:"varint,2,opt,name=message_status,json=messageStatus,proto3" json:"message_status,omitempty"`
}

func (x *MessagePostResponse) Reset() {
	*x = MessagePostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_post_message_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePostResponse) ProtoMessage() {}

func (x *MessagePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_post_message_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePostResponse.ProtoReflect.Descriptor instead.
func (*MessagePostResponse) Descriptor() ([]byte, []int) {
	return file_message_post_message_post_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePostResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessagePostResponse) GetMessageStatus() int32 {
	if x != nil {
		return x.MessageStatus
	}
	return 0
}

var File_message_post_message_post_proto protoreflect.FileDescriptor

var file_message_post_message_post_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x22,
	0x9c, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x43,
	0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0x6a, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x3b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_message_post_message_post_proto_rawDescOnce sync.Once
	file_message_post_message_post_proto_rawDescData = file_message_post_message_post_proto_rawDesc
)

func file_message_post_message_post_proto_rawDescGZIP() []byte {
	file_message_post_message_post_proto_rawDescOnce.Do(func() {
		file_message_post_message_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_post_message_post_proto_rawDescData)
	})
	return file_message_post_message_post_proto_rawDescData
}

var file_message_post_message_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_post_message_post_proto_goTypes = []interface{}{
	(*MessagePost)(nil),         // 0: message_post.MessagePost
	(*MessagePostRequest)(nil),  // 1: message_post.MessagePostRequest
	(*MessagePostResponse)(nil), // 2: message_post.MessagePostResponse
}
var file_message_post_message_post_proto_depIdxs = []int32{
	0, // 0: message_post.MessagePostRequest.post:type_name -> message_post.MessagePost
	1, // 1: message_post.MessagePostService.MessagePost:input_type -> message_post.MessagePostRequest
	2, // 2: message_post.MessagePostService.MessagePost:output_type -> message_post.MessagePostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_post_message_post_proto_init() }
func file_message_post_message_post_proto_init() {
	if File_message_post_message_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_post_message_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_post_message_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_post_message_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagePostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_post_message_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_post_message_post_proto_goTypes,
		DependencyIndexes: file_message_post_message_post_proto_depIdxs,
		MessageInfos:      file_message_post_message_post_proto_msgTypes,
	}.Build()
	File_message_post_message_post_proto = out.File
	file_message_post_message_post_proto_rawDesc = nil
	file_message_post_message_post_proto_goTypes = nil
	file_message_post_message_post_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessagePostServiceClient is the client API for MessagePostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagePostServiceClient interface {
	MessagePost(ctx context.Context, in *MessagePostRequest, opts ...grpc.CallOption) (*MessagePostResponse, error)
}

type messagePostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagePostServiceClient(cc grpc.ClientConnInterface) MessagePostServiceClient {
	return &messagePostServiceClient{cc}
}

func (c *messagePostServiceClient) MessagePost(ctx context.Context, in *MessagePostRequest, opts ...grpc.CallOption) (*MessagePostResponse, error) {
	out := new(MessagePostResponse)
	err := c.cc.Invoke(ctx, "/message_post.MessagePostService/MessagePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagePostServiceServer is the server API for MessagePostService service.
type MessagePostServiceServer interface {
	MessagePost(context.Context, *MessagePostRequest) (*MessagePostResponse, error)
}

// UnimplementedMessagePostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessagePostServiceServer struct {
}

func (*UnimplementedMessagePostServiceServer) MessagePost(context.Context, *MessagePostRequest) (*MessagePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessagePost not implemented")
}

func RegisterMessagePostServiceServer(s *grpc.Server, srv MessagePostServiceServer) {
	s.RegisterService(&_MessagePostService_serviceDesc, srv)
}

func _MessagePostService_MessagePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePostServiceServer).MessagePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message_post.MessagePostService/MessagePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePostServiceServer).MessagePost(ctx, req.(*MessagePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessagePostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message_post.MessagePostService",
	HandlerType: (*MessagePostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessagePost",
			Handler:    _MessagePostService_MessagePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message-post/message-post.proto",
}
